# Generated by Django 4.2.5 on 2023-09-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='aces',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='isWinner',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='stats',
            name='drillPercent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='drillsComplete',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='totalDrills',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='@.com', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='/', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
    ]
