# Generated by Django 4.2.5 on 2023-10-01 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_stats_drillpercent_remove_stats_totaldrills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='drillsComplete',
        ),
        migrations.AddField(
            model_name='stats',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stats',
            name='text',
            field=models.CharField(default='', max_length=300),
        ),
    ]
