# Generated by Django 4.2.5 on 2023-10-02 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_stats_drillscomplete_stats_complete_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='text',
        ),
        migrations.AddField(
            model_name='stats',
            name='drillsComplete',
            field=models.IntegerField(default=0),
        ),
    ]
