# Generated by Django 3.2.2 on 2023-11-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_stats_complete_remove_stats_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drill_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('drill_name', models.CharField(max_length=20)),
                ('amount_completed', models.IntegerField(max_length=20)),
            ],
        ),
    ]
