# Generated by Django 4.2.5 on 2023-11-06 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_drill_data'),
        ('main_app', '0006_message'),
    ]

    operations = [
    ]
